/* Generated by Yosys 0.35+36 (git sha1 c95298225, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module thermometer_to_binary(p, b);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  output [3:0] b;
  wire [3:0] b;
  input [14:0] p;
  wire [14:0] p;
  sky130_fd_sc_hd__clkinv_1 _149_ (
    .A(_135_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand2_1 _150_ (
    .A(_140_),
    .B(_134_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand3_1 _151_ (
    .A(_140_),
    .B(_134_),
    .C(_141_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand4_1 _152_ (
    .A(_140_),
    .B(_134_),
    .C(_142_),
    .D(_141_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nand2_1 _153_ (
    .A(_144_),
    .B(_143_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nand4_1 _154_ (
    .A(_144_),
    .B(_143_),
    .C(_146_),
    .D(_145_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nor2_1 _155_ (
    .A(_101_),
    .B(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand2_1 _156_ (
    .A(_147_),
    .B(_148_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nand2_1 _157_ (
    .A(_136_),
    .B(_135_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nor4_1 _158_ (
    .A(_101_),
    .B(_103_),
    .C(_105_),
    .D(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__and2_0 _159_ (
    .A(_138_),
    .B(_137_),
    .X(_108_)
  );
  sky130_fd_sc_hd__nand2_1 _160_ (
    .A(_107_),
    .B(_108_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand3_1 _161_ (
    .A(_139_),
    .B(_107_),
    .C(_108_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nor2_1 _162_ (
    .A(_146_),
    .B(_102_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nor3_1 _163_ (
    .A(_144_),
    .B(_146_),
    .C(_145_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a22oi_1 _164_ (
    .A1(_145_),
    .A2(_111_),
    .B1(_112_),
    .B2(_143_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nor2_1 _165_ (
    .A(_138_),
    .B(_139_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__or3_1 _166_ (
    .A(_138_),
    .B(_137_),
    .C(_139_),
    .X(_115_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _167_ (
    .A(_136_),
    .SLEEP(_135_),
    .X(_116_)
  );
  sky130_fd_sc_hd__nor4_1 _168_ (
    .A(_147_),
    .B(_148_),
    .C(_115_),
    .D(_116_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nand2b_1 _169_ (
    .A_N(_101_),
    .B(_117_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nor4b_1 _170_ (
    .A(_148_),
    .B(_115_),
    .C(_116_),
    .D_N(_147_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nor3_1 _171_ (
    .A(_136_),
    .B(_105_),
    .C(_115_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nor4_1 _172_ (
    .A(_136_),
    .B(_098_),
    .C(_105_),
    .D(_115_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__o21ai_0 _173_ (
    .A1(_119_),
    .A2(_121_),
    .B1(_104_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__or3b_1 _174_ (
    .A(_140_),
    .B(_141_),
    .C_N(_134_),
    .X(_123_)
  );
  sky130_fd_sc_hd__or4_1 _175_ (
    .A(_144_),
    .B(_143_),
    .C(_146_),
    .D(_145_),
    .X(_124_)
  );
  sky130_fd_sc_hd__a211oi_1 _176_ (
    .A1(_100_),
    .A2(_123_),
    .B1(_124_),
    .C1(_142_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__a32oi_1 _177_ (
    .A1(_137_),
    .A2(_107_),
    .A3(_114_),
    .B1(_117_),
    .B2(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__o2111ai_1 _178_ (
    .A1(_113_),
    .A2(_118_),
    .B1(_122_),
    .C1(_126_),
    .D1(_110_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nand3b_1 _179_ (
    .A_N(_101_),
    .B(_111_),
    .C(_117_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nand2_1 _180_ (
    .A(_104_),
    .B(_120_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nor3_1 _181_ (
    .A(_142_),
    .B(_099_),
    .C(_124_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand2_1 _182_ (
    .A(_117_),
    .B(_129_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nand4_1 _183_ (
    .A(_109_),
    .B(_127_),
    .C(_128_),
    .D(_130_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__o21ai_0 _184_ (
    .A1(_108_),
    .A2(_114_),
    .B1(_107_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nor2_1 _185_ (
    .A(_111_),
    .B(_112_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__o21ai_0 _186_ (
    .A1(_118_),
    .A2(_132_),
    .B1(_131_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__o31ai_1 _187_ (
    .A1(_117_),
    .A2(_119_),
    .A3(_120_),
    .B1(_104_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nand2_1 _188_ (
    .A(_131_),
    .B(_133_),
    .Y(_097_)
  );
  assign _140_ = p[1];
  assign _134_ = p[0];
  assign _142_ = p[3];
  assign _141_ = p[2];
  assign _144_ = p[5];
  assign _143_ = p[4];
  assign _146_ = p[7];
  assign _145_ = p[6];
  assign _147_ = p[8];
  assign _148_ = p[9];
  assign _136_ = p[11];
  assign _135_ = p[10];
  assign _138_ = p[13];
  assign _137_ = p[12];
  assign _139_ = p[14];
  assign b[0] = _094_;
  assign b[1] = _095_;
  assign b[2] = _096_;
  assign b[3] = _097_;
endmodule
