/* Generated by Yosys 0.35+36 (git sha1 c95298225, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

(* top =  1  *)
(* src = "therm_code.v:1.1-28.10" *)
module thermometer_to_binary(inverted_thermometer, binary);
  (* src = "therm_code.v:3.22-3.28" *)
  wire _000_;
  (* src = "therm_code.v:3.22-3.28" *)
  wire _001_;
  (* src = "therm_code.v:3.22-3.28" *)
  wire _002_;
  (* src = "therm_code.v:3.22-3.28" *)
  wire _003_;
  (* src = "therm_code.v:2.18-2.38" *)
  wire _004_;
  (* src = "therm_code.v:2.18-2.38" *)
  wire _005_;
  (* src = "therm_code.v:2.18-2.38" *)
  wire _006_;
  (* src = "therm_code.v:2.18-2.38" *)
  wire _007_;
  (* src = "therm_code.v:2.18-2.38" *)
  wire _008_;
  (* src = "therm_code.v:2.18-2.38" *)
  wire _009_;
  (* src = "therm_code.v:2.18-2.38" *)
  wire _010_;
  (* src = "therm_code.v:2.18-2.38" *)
  wire _011_;
  (* src = "therm_code.v:2.18-2.38" *)
  wire _012_;
  (* src = "therm_code.v:2.18-2.38" *)
  wire _013_;
  (* src = "therm_code.v:2.18-2.38" *)
  wire _014_;
  (* src = "therm_code.v:2.18-2.38" *)
  wire _015_;
  (* src = "therm_code.v:2.18-2.38" *)
  wire _016_;
  (* src = "therm_code.v:2.18-2.38" *)
  wire _017_;
  (* src = "therm_code.v:2.18-2.38" *)
  wire _018_;
  (* src = "therm_code.v:2.18-2.38" *)
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  (* src = "therm_code.v:3.22-3.28" *)
  output [3:0] binary;
  wire [3:0] binary;
  (* src = "therm_code.v:2.18-2.38" *)
  input [15:0] inverted_thermometer;
  wire [15:0] inverted_thermometer;
  sky130_fd_sc_hs__clkinv_1 _143_ (
    .A(_019_),
    .Y(_020_)
  );
  sky130_fd_sc_hs__nand2_1 _144_ (
    .A(_006_),
    .B(_005_),
    .Y(_021_)
  );
  sky130_fd_sc_hs__nand4_1 _145_ (
    .A(_019_),
    .B(_018_),
    .C(_006_),
    .D(_005_),
    .Y(_022_)
  );
  sky130_fd_sc_hs__nand4_1 _146_ (
    .A(_008_),
    .B(_007_),
    .C(_010_),
    .D(_009_),
    .Y(_023_)
  );
  sky130_fd_sc_hs__nor2_1 _147_ (
    .A(_011_),
    .B(_004_),
    .Y(_024_)
  );
  sky130_fd_sc_hs__nor3_1 _148_ (
    .A(_013_),
    .B(_011_),
    .C(_004_),
    .Y(_025_)
  );
  sky130_fd_sc_hs__nor2_1 _149_ (
    .A(_014_),
    .B(_015_),
    .Y(_026_)
  );
  sky130_fd_sc_hs__nor3_1 _150_ (
    .A(_014_),
    .B(_015_),
    .C(_016_),
    .Y(_027_)
  );
  sky130_fd_sc_hs__or4_1 _151_ (
    .A(_012_),
    .B(_013_),
    .C(_011_),
    .D(_004_),
    .X(_028_)
  );
  sky130_fd_sc_hs__or4_1 _152_ (
    .A(_014_),
    .B(_015_),
    .C(_017_),
    .D(_016_),
    .X(_029_)
  );
  sky130_fd_sc_hs__nor3_1 _153_ (
    .A(_023_),
    .B(_028_),
    .C(_029_),
    .Y(_030_)
  );
  sky130_fd_sc_hs__nor4_1 _154_ (
    .A(_022_),
    .B(_023_),
    .C(_028_),
    .D(_029_),
    .Y(_031_)
  );
  sky130_fd_sc_hs__nor3_1 _155_ (
    .A(_012_),
    .B(_022_),
    .C(_023_),
    .Y(_032_)
  );
  sky130_fd_sc_hs__nor4b_1 _156_ (
    .A(_012_),
    .B(_022_),
    .C(_023_),
    .D_N(_025_),
    .Y(_033_)
  );
  sky130_fd_sc_hs__and4_1 _157_ (
    .A(_014_),
    .B(_015_),
    .C(_017_),
    .D(_016_),
    .X(_034_)
  );
  sky130_fd_sc_hs__nand2_1 _158_ (
    .A(_033_),
    .B(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hs__nor3_1 _159_ (
    .A(_019_),
    .B(_018_),
    .C(_005_),
    .Y(_036_)
  );
  sky130_fd_sc_hs__or4_1 _160_ (
    .A(_019_),
    .B(_018_),
    .C(_006_),
    .D(_005_),
    .X(_037_)
  );
  sky130_fd_sc_hs__nand4_1 _161_ (
    .A(_017_),
    .B(_016_),
    .C(_026_),
    .D(_033_),
    .Y(_038_)
  );
  sky130_fd_sc_hs__nor2_1 _162_ (
    .A(_018_),
    .B(_021_),
    .Y(_039_)
  );
  sky130_fd_sc_hs__nand2_1 _163_ (
    .A(_030_),
    .B(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hs__nor3_1 _164_ (
    .A(_008_),
    .B(_007_),
    .C(_009_),
    .Y(_041_)
  );
  sky130_fd_sc_hs__nor4b_1 _165_ (
    .A(_028_),
    .B(_029_),
    .C(_037_),
    .D_N(_041_),
    .Y(_042_)
  );
  sky130_fd_sc_hs__nand2b_1 _166_ (
    .A_N(_010_),
    .B(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hs__nand3b_1 _167_ (
    .A_N(_007_),
    .B(_010_),
    .C(_009_),
    .Y(_044_)
  );
  sky130_fd_sc_hs__or4_1 _168_ (
    .A(_028_),
    .B(_029_),
    .C(_037_),
    .D(_044_),
    .X(_045_)
  );
  sky130_fd_sc_hs__nor4_1 _169_ (
    .A(_023_),
    .B(_028_),
    .C(_029_),
    .D(_037_),
    .Y(_046_)
  );
  sky130_fd_sc_hs__a311oi_1 _170_ (
    .A1(_020_),
    .A2(_030_),
    .A3(_039_),
    .B1(_046_),
    .C1(_031_),
    .Y(_047_)
  );
  sky130_fd_sc_hs__a2bb2oi_1 _171_ (
    .A1_N(_008_),
    .A2_N(_045_),
    .B1(_034_),
    .B2(_033_),
    .Y(_048_)
  );
  sky130_fd_sc_hs__nand4_1 _172_ (
    .A(_038_),
    .B(_043_),
    .C(_047_),
    .D(_048_),
    .Y(_000_)
  );
  sky130_fd_sc_hs__a21oi_1 _173_ (
    .A1(_030_),
    .A2(_036_),
    .B1(_042_),
    .Y(_049_)
  );
  sky130_fd_sc_hs__a41oi_1 _174_ (
    .A1(_017_),
    .A2(_025_),
    .A3(_027_),
    .A4(_032_),
    .B1(_031_),
    .Y(_050_)
  );
  sky130_fd_sc_hs__nand4_1 _175_ (
    .A(_013_),
    .B(_024_),
    .C(_032_),
    .D(_034_),
    .Y(_051_)
  );
  sky130_fd_sc_hs__nand4_1 _176_ (
    .A(_035_),
    .B(_049_),
    .C(_050_),
    .D(_051_),
    .Y(_001_)
  );
  sky130_fd_sc_hs__nand4b_1 _177_ (
    .A_N(_014_),
    .B(_017_),
    .C(_016_),
    .D(_033_),
    .Y(_052_)
  );
  sky130_fd_sc_hs__nand4b_1 _178_ (
    .A_N(_042_),
    .B(_045_),
    .C(_050_),
    .D(_052_),
    .Y(_002_)
  );
  sky130_fd_sc_hs__nand3_1 _179_ (
    .A(_040_),
    .B(_045_),
    .C(_049_),
    .Y(_003_)
  );
  assign _014_ = inverted_thermometer[4];
  assign _015_ = inverted_thermometer[5];
  assign _017_ = inverted_thermometer[7];
  assign _016_ = inverted_thermometer[6];
  assign _019_ = inverted_thermometer[9];
  assign _018_ = inverted_thermometer[8];
  assign _006_ = inverted_thermometer[11];
  assign _005_ = inverted_thermometer[10];
  assign _008_ = inverted_thermometer[13];
  assign _007_ = inverted_thermometer[12];
  assign _010_ = inverted_thermometer[15];
  assign _009_ = inverted_thermometer[14];
  assign _012_ = inverted_thermometer[2];
  assign _013_ = inverted_thermometer[3];
  assign binary[0] = _000_;
  assign binary[1] = _001_;
  assign binary[2] = _002_;
  assign binary[3] = _003_;
  assign _011_ = inverted_thermometer[1];
  assign _004_ = inverted_thermometer[0];
endmodule
