
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Feb  7 2025 23:35:42 CET (Feb  7 2025 22:35:42 UTC)

// Verification Directory fv/thermometer 

module thermometer(Y, b, clk, rst);
  input [14:0] Y;
  input clk, rst;
  output [3:0] b;
  wire [14:0] Y;
  wire clk, rst;
  wire [3:0] b;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, n_0, n_1,
       n_2, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_16, n_17, n_20, n_21, n_22, n_23;
  CLKBUFX8 g265(.A (n_23), .Y (b[0]));
  DFFRX1 \out_reg[0] (.RN (n_17), .CK (clk), .D (n_16), .Q (n_23), .QN
       (UNCONNECTED));
  CLKBUFX8 g267(.A (n_22), .Y (b[1]));
  DFFRX1 \out_reg[1] (.RN (n_17), .CK (clk), .D (n_14), .Q (n_22), .QN
       (UNCONNECTED0));
  NAND4X1 g268__2398(.A (n_13), .B (n_11), .C (n_7), .D (n_10), .Y
       (n_16));
  CLKBUFX8 g270(.A (n_21), .Y (b[2]));
  DFFRX1 \out_reg[2] (.RN (n_17), .CK (clk), .D (n_9), .Q (n_21), .QN
       (UNCONNECTED1));
  OAI221X1 g271__5107(.A0 (Y[7]), .A1 (n_12), .B0 (Y[11]), .B1 (n_6),
       .C0 (n_4), .Y (n_14));
  AOI21X1 g274__6260(.A0 (Y[4]), .A1 (n_12), .B0 (Y[14]), .Y (n_13));
  AOI22X1 g275__4319(.A0 (Y[2]), .A1 (n_8), .B0 (Y[6]), .B1 (n_0), .Y
       (n_11));
  AOI22X1 g276__8428(.A0 (Y[0]), .A1 (n_1), .B0 (Y[12]), .B1 (n_2), .Y
       (n_10));
  OAI21X1 g273__5526(.A0 (Y[7]), .A1 (n_8), .B0 (n_5), .Y (n_9));
  AOI22X1 g277__6783(.A0 (Y[8]), .A1 (n_6), .B0 (Y[10]), .B1 (n_5), .Y
       (n_7));
  AOI21X1 g272__3680(.A0 (Y[1]), .A1 (n_8), .B0 (Y[13]), .Y (n_4));
  CLKBUFX8 g279(.A (n_20), .Y (b[3]));
  DFFRX1 \out_reg[3] (.RN (n_17), .CK (clk), .D (Y[7]), .Q (n_20), .QN
       (UNCONNECTED2));
  INVX1 g284(.A (Y[13]), .Y (n_2));
  INVX1 g280(.A (Y[1]), .Y (n_1));
  CLKINVX2 g285(.A (Y[9]), .Y (n_6));
  CLKINVX2 g281(.A (Y[11]), .Y (n_5));
  CLKINVX2 g287(.A (Y[7]), .Y (n_0));
  CLKINVX2 g283(.A (Y[5]), .Y (n_12));
  CLKINVX2 g282(.A (Y[3]), .Y (n_8));
  CLKINVX1 g286(.A (rst), .Y (n_17));
endmodule

