
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Feb  9 2025 17:54:16 CET (Feb  9 2025 16:54:16 UTC)

// Verification Directory fv/thermometer 

module thermometer(Y, b, clk, rst);
  input [14:0] Y;
  input clk, rst;
  output [3:0] b;
  wire [14:0] Y;
  wire clk, rst;
  wire [3:0] b;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, n_0, n_1,
       n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_42, n_43, n_47;
  wire n_48, n_49, n_50;
  CLKBUFX8 g1017(.A (n_48), .Y (b[2]));
  DFFRX1 \out_reg[2] (.RN (n_43), .CK (clk), .D (n_42), .Q (n_48), .QN
       (UNCONNECTED));
  CLKBUFX8 g1013(.A (n_50), .Y (b[0]));
  CLKBUFX8 g1015(.A (n_49), .Y (b[3]));
  DFFRX1 \out_reg[0] (.RN (n_43), .CK (clk), .D (n_40), .Q (n_50), .QN
       (UNCONNECTED0));
  NAND3X1 g1022__2398(.A (n_31), .B (n_37), .C (n_29), .Y (n_42));
  DFFRX1 \out_reg[3] (.RN (n_43), .CK (clk), .D (n_39), .Q (n_49), .QN
       (UNCONNECTED1));
  CLKBUFX8 g1019(.A (n_47), .Y (b[1]));
  OAI21X1 g1020__5107(.A0 (n_10), .A1 (n_38), .B0 (n_34), .Y (n_40));
  OAI221X1 g1024__6260(.A0 (n_35), .A1 (n_38), .B0 (n_23), .B1 (n_19),
       .C0 (n_32), .Y (n_39));
  DFFRX1 \out_reg[1] (.RN (n_43), .CK (clk), .D (n_33), .Q (n_47), .QN
       (UNCONNECTED2));
  INVX1 g1025(.A (n_36), .Y (n_37));
  AOI21X1 g1026__4319(.A0 (n_4), .A1 (n_35), .B0 (n_38), .Y (n_36));
  AOI222X1 g1023__8428(.A0 (n_26), .A1 (n_25), .B0 (n_15), .B1 (n_30),
       .C0 (n_17), .C1 (n_28), .Y (n_34));
  NAND3X1 g1021__5526(.A (n_32), .B (n_31), .C (n_27), .Y (n_33));
  OAI21X1 g1027__6783(.A0 (n_9), .A1 (n_16), .B0 (n_30), .Y (n_32));
  NAND2X1 g1028__3680(.A (n_8), .B (n_30), .Y (n_38));
  NAND3X1 g1030__1617(.A (Y[3]), .B (n_12), .C (n_28), .Y (n_29));
  NAND4X1 g1029__2802(.A (Y[0]), .B (Y[1]), .C (n_11), .D (n_28), .Y
       (n_27));
  AND4X2 g1034__1705(.A (Y[8]), .B (Y[9]), .C (Y[7]), .D (n_26), .Y
       (n_30));
  NAND3X1 g1033__5122(.A (Y[5]), .B (n_20), .C (n_22), .Y (n_31));
  NAND2X1 g1031__8246(.A (n_21), .B (n_24), .Y (n_25));
  NOR3X1 g1035__7098(.A (Y[5]), .B (Y[6]), .C (n_24), .Y (n_28));
  CLKINVX1 g1039(.A (n_23), .Y (n_26));
  CLKINVX1 g1038(.A (n_24), .Y (n_22));
  NAND3X1 g1040__6131(.A (Y[7]), .B (Y[8]), .C (n_18), .Y (n_21));
  NAND3X1 g1042__1881(.A (Y[5]), .B (Y[6]), .C (n_20), .Y (n_23));
  NAND2X1 g1036__5115(.A (Y[7]), .B (n_18), .Y (n_19));
  NAND2X1 g1041__7482(.A (n_2), .B (n_18), .Y (n_24));
  NAND2X1 g1032__4733(.A (n_14), .B (n_13), .Y (n_17));
  CLKAND2X2 g1047__6161(.A (n_0), .B (n_16), .Y (n_18));
  AND2X1 g1044__9315(.A (n_16), .B (Y[10]), .Y (n_15));
  CLKINVX2 g1043(.A (n_14), .Y (n_20));
  OAI21X1 g1037__9945(.A0 (n_12), .A1 (n_6), .B0 (n_11), .Y (n_13));
  NAND3X1 g1045__2883(.A (Y[3]), .B (Y[4]), .C (n_12), .Y (n_14));
  AOI22X1 g1046__2346(.A0 (Y[12]), .A1 (n_3), .B0 (Y[14]), .B1 (n_7),
       .Y (n_10));
  NOR3X1 g1050__1666(.A (Y[11]), .B (Y[12]), .C (n_35), .Y (n_16));
  AND2X1 g1048__7410(.A (n_8), .B (n_7), .Y (n_9));
  NOR3X1 g1049__6417(.A (Y[1]), .B (Y[2]), .C (n_5), .Y (n_6));
  NOR2X4 g1051__5477(.A (n_5), .B (n_1), .Y (n_12));
  INVX1 g1056(.A (n_4), .Y (n_7));
  CLKINVX2 g1052(.A (n_3), .Y (n_35));
  NOR2X1 g1054__2398(.A (Y[7]), .B (Y[8]), .Y (n_2));
  NAND2X1 g1060__5107(.A (Y[12]), .B (Y[13]), .Y (n_4));
  AND2X1 g1059__6260(.A (Y[11]), .B (Y[10]), .Y (n_8));
  NAND2X2 g1053__4319(.A (Y[1]), .B (Y[2]), .Y (n_1));
  NOR2X1 g1057__8428(.A (Y[9]), .B (Y[10]), .Y (n_0));
  NOR2X1 g1058__5526(.A (Y[3]), .B (Y[4]), .Y (n_11));
  NOR2X2 g1055__6783(.A (Y[13]), .B (Y[14]), .Y (n_3));
  CLKINVX2 g1061(.A (Y[0]), .Y (n_5));
  INVX1 g1062(.A (rst), .Y (n_43));
endmodule

