/*
###############################################################
#  Generated by:      Cadence Innovus 23.31-s109_1
#  OS:                Linux x86_64(Host ID cae-europractice1.othr.de)
#  Generated on:      Sun Feb  9 18:49:10 2025
#  Design:            thermometer
#  Command:           saveNetlist post_layout_thermometer.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 23.11-s100_1
// Generated on: Feb  7 2025 23:35:42 CET (Feb  7 2025 22:35:42 UTC)
// Verification Directory fv/thermometer 
module thermometer (
	Y, 
	b, 
	clk, 
	rst);
   input [14:0] Y;
   output [3:0] b;
   input clk;
   input rst;

   // Internal wires
   wire FE_OFN3_b_0;
   wire FE_OFN2_b_1;
   wire FE_OFN1_b_2;
   wire FE_OFN0_b_3;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_16;
   wire n_17;

   BUFX16 FE_OFC3_b_0 (.Y(b[0]),
	.A(FE_OFN3_b_0));
   BUFX16 FE_OFC2_b_1 (.Y(b[1]),
	.A(FE_OFN2_b_1));
   BUFX16 FE_OFC1_b_2 (.Y(b[2]),
	.A(FE_OFN1_b_2));
   BUFX16 FE_OFC0_b_3 (.Y(b[3]),
	.A(FE_OFN0_b_3));
   DFFRX1 \out_reg[0]  (.Q(FE_OFN3_b_0),
	.QN(UNCONNECTED),
	.CK(clk),
	.D(n_16),
	.RN(n_17));
   DFFRX1 \out_reg[1]  (.Q(FE_OFN2_b_1),
	.QN(UNCONNECTED0),
	.CK(clk),
	.D(n_14),
	.RN(n_17));
   NAND4X1 g268__2398 (.Y(n_16),
	.A(n_13),
	.B(n_11),
	.C(n_7),
	.D(n_10));
   DFFRX1 \out_reg[2]  (.Q(FE_OFN1_b_2),
	.QN(UNCONNECTED1),
	.CK(clk),
	.D(n_9),
	.RN(n_17));
   OAI221X1 g271__5107 (.Y(n_14),
	.A0(Y[7]),
	.A1(n_12),
	.B0(Y[11]),
	.B1(n_6),
	.C0(n_4));
   AOI21X1 g274__6260 (.Y(n_13),
	.A0(Y[4]),
	.A1(n_12),
	.B0(Y[14]));
   AOI22X1 g275__4319 (.Y(n_11),
	.A0(Y[2]),
	.A1(n_8),
	.B0(Y[6]),
	.B1(n_0));
   AOI22X1 g276__8428 (.Y(n_10),
	.A0(Y[0]),
	.A1(n_1),
	.B0(Y[12]),
	.B1(n_2));
   OAI21X1 g273__5526 (.Y(n_9),
	.A0(Y[7]),
	.A1(n_8),
	.B0(n_5));
   AOI22X1 g277__6783 (.Y(n_7),
	.A0(Y[8]),
	.A1(n_6),
	.B0(Y[10]),
	.B1(n_5));
   AOI21X1 g272__3680 (.Y(n_4),
	.A0(Y[1]),
	.A1(n_8),
	.B0(Y[13]));
   DFFRX1 \out_reg[3]  (.Q(FE_OFN0_b_3),
	.QN(UNCONNECTED2),
	.CK(clk),
	.D(Y[7]),
	.RN(n_17));
   INVX1 g284 (.Y(n_2),
	.A(Y[13]));
   INVX1 g280 (.Y(n_1),
	.A(Y[1]));
   CLKINVX2 g285 (.Y(n_6),
	.A(Y[9]));
   CLKINVX2 g281 (.Y(n_5),
	.A(Y[11]));
   CLKINVX2 g287 (.Y(n_0),
	.A(Y[7]));
   CLKINVX2 g283 (.Y(n_12),
	.A(Y[5]));
   CLKINVX2 g282 (.Y(n_8),
	.A(Y[3]));
   CLKINVX1 g286 (.Y(n_17),
	.A(rst));
endmodule

