
// Generated by Cadence Genus(TM) Synthesis Solution 22.13-s093_1
// Generated on: Dec 12 2024 22:24:20 CET (Dec 12 2024 21:24:20 UTC)

// Verification Directory fv/adc 

module pre_therm(IN, Y01, Y02, Y03, Y04, Y05, Y06, Y07, Y08, Y09, Y10,
     Y11, Y12, Y13, Y14, Y15);
  input IN;
  output Y01, Y02, Y03, Y04, Y05, Y06, Y07, Y08, Y09, Y10, Y11, Y12,
       Y13, Y14, Y15;
  wire IN;
  wire Y01, Y02, Y03, Y04, Y05, Y06, Y07, Y08, Y09, Y10, Y11, Y12, Y13,
       Y14, Y15;
endmodule

module therm(Y, b, clk, rst);
  input [14:0] Y;
  input clk, rst;
  output [3:0] b;
  wire [14:0] Y;
  wire clk, rst;
  wire [3:0] b;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, n_0, n_1,
       n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20;
  DFFRX1 \out_reg[0] (.RN (n_1), .CK (clk), .D (n_18), .Q (n_20), .QN
       (UNCONNECTED));
  CLKBUFX8 g294(.A (n_20), .Y (b[0]));
  DFFRX1 \out_reg[1] (.RN (n_1), .CK (clk), .D (n_16), .Q (n_19), .QN
       (UNCONNECTED0));
  CLKBUFX8 g296(.A (n_19), .Y (b[1]));
  NAND4X1 g297__2398(.A (Y[14]), .B (n_9), .C (n_12), .D (n_15), .Y
       (n_18));
  DFFRX1 \out_reg[2] (.RN (n_1), .CK (clk), .D (n_14), .Q (n_17), .QN
       (UNCONNECTED1));
  CLKBUFX8 g299(.A (n_17), .Y (b[2]));
  OAI211X1 g300__5107(.A0 (Y[5]), .A1 (n_0), .B0 (Y[13]), .C0 (n_13),
       .Y (n_16));
  AOI221X1 g301__6260(.A0 (Y[1]), .A1 (n_3), .B0 (Y[5]), .B1 (n_7), .C0
       (n_11), .Y (n_15));
  OAI21X1 g302__4319(.A0 (Y[3]), .A1 (n_0), .B0 (Y[11]), .Y (n_14));
  AOI22X1 g303__8428(.A0 (Y[3]), .A1 (n_6), .B0 (Y[11]), .B1 (n_2), .Y
       (n_13));
  AOI22X1 g304__5526(.A0 (Y[3]), .A1 (n_8), .B0 (Y[13]), .B1 (n_4), .Y
       (n_12));
  OAI22X1 g305__6783(.A0 (Y[6]), .A1 (n_0), .B0 (Y[10]), .B1 (n_5), .Y
       (n_11));
  DFFRX1 \out_reg[3] (.RN (n_1), .CK (clk), .D (n_0), .Q (n_10), .QN
       (UNCONNECTED2));
  CLKBUFX8 g307(.A (n_10), .Y (b[3]));
  OR2X1 g308__3680(.A (Y[8]), .B (n_2), .Y (n_9));
  CLKINVX2 g309(.A (Y[2]), .Y (n_8));
  CLKINVX2 g310(.A (Y[4]), .Y (n_7));
  INVX1 g311(.A (Y[1]), .Y (n_6));
  INVX2 g312(.A (Y[11]), .Y (n_5));
  CLKINVX2 g313(.A (Y[12]), .Y (n_4));
  CLKINVX2 g314(.A (Y[0]), .Y (n_3));
  CLKINVX2 g315(.A (Y[9]), .Y (n_2));
  CLKINVX1 g316(.A (rst), .Y (n_1));
  INVX2 g317(.A (Y[7]), .Y (n_0));
endmodule

module adc(IN, b, clk, rst);
  input IN, clk, rst;
  output [3:0] b;
  wire IN, clk, rst;
  wire [3:0] b;
  wire [14:0] int;
  pre_therm pretherm(.IN (IN), .Y01 (int[0]), .Y02 (int[1]), .Y03
       (int[2]), .Y04 (int[3]), .Y05 (int[4]), .Y06 (int[5]), .Y07
       (int[6]), .Y08 (int[7]), .Y09 (int[8]), .Y10 (int[9]), .Y11
       (int[10]), .Y12 (int[11]), .Y13 (int[12]), .Y14 (int[13]), .Y15
       (int[14]));
  therm therm1(.Y (int), .b (b), .clk (clk), .rst (rst));
endmodule

